### ISSUE TITLE
Bake Variable Not Resolving within Array of Objects

### ISSUE THREAD

**Issue by bdschaap** [HomecareHomebase/azure-bake#116]
A Bake variable that's referenced within an array of objects does not resolve the variable.  Instead, it passes a literal string of _[coreutils.variable('OPS_GENIE_AZURE_MONITOR_API_URL')]_ to the arm template.

**Bake Recipe snippet**
```yaml
      parameters:
        actionGroupName: "[coreutils.create_resource_name('act','opsgenie', false)]"
        actionGroupShortName: "opsgenie"
        webhookReceivers:
        - name: opsgenieHook
          serviceUri: "[coreutils.variable('OPS_GENIE_AZURE_MONITOR_API_URL')]"
```
