### ISSUE TITLE
Bake does not appear to support arrays

### ISSUE THREAD

**Issue by bdschaap** [HomecareHomebase/azure-bake#47]
Recipes don't appear to support params that are arrays.

**bake.yaml snippet**
```yaml
parameters:
   policyRights:
      - Listen
      - Send
```

Mon, 15 Apr 2019 20:09:08 GMT] East US : ehdiag-deploy deployment failed: TypeError: variable.Code.trim is not a function
[Mon, 15 Apr 2019 20:09:08 GMT] TypeError: variable.Code.trim is not a function

**ARM Template snippet**
```json
"parameters": {
    "policyRights": {
      "type": "array",
      "defaultValue": [
        "Listen",
        "Send"
      ]
    }
}
```
